const SHOP_DATA = {
  hats: {
    id: 1,
    title: "Hats",
    routeName: "hats",
    imageUrl: "https://i.ibb.co/cvpntL1/hats.png",
    linkUrl: "creations/hats",
    items: [
      {
        id: 1,
        title: "Badinedonpas",
        category: "hats",
        routeName: "brown-brim",
        price: 26.0,
        cartQuantity: 0,
        shortDescription:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
        stock: 1,
        bulletPoints: [
          "this is a bullet point",
          "this is another bullet point",
          "anotherbulletPoint...",
        ],
        linkUrl: "hats/brown-brim",
        imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
      },
      {
        id: 2,
        title: "Stoen salapaitch",
        routeName: "stoen-salapaitch",
        linkUrl: "hats/stoen-salapaitch",
        imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 18,
      },
      {
        id: 3,
        title: "Brown Cowboy",
        routeName: "brown-cowboy",
        linkUrl: "hats/brown-cowboy",
        imageUrl: "https://i.ibb.co/QdJwgmp/brown-cowboy.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 35,
      },
      {
        id: 4,
        title: "Grey Brim",
        routeName: "grey-brim",
        linkUrl: "hats/grey-brim",
        imageUrl: "https://i.ibb.co/RjBLWxB/grey-brim.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 25,
      },
      {
        id: 5,
        title: "Green Beanie",
        routeName: "green-beanie",
        linkUrl: "hats/green-beanie",
        imageUrl: "https://i.ibb.co/YTjW3vF/green-beanie.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 18,
      },
      {
        id: 6,
        title: "Palm Tree Cap",
        routeName: "palm-tree-cap",
        linkUrl: "hats/palm-tree-cap",
        imageUrl: "https://i.ibb.co/rKBDvJX/palm-tree-cap.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 14,
      },
      {
        id: 7,
        title: "Red Beanie",
        routeName: "red-beanie",
        linkUrl: "hats/red-beanie",
        imageUrl: "https://i.ibb.co/bLB646Z/red-beanie.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 18,
      },
      {
        id: 8,
        title: "Wolf Cap",
        routeName: "wolf-cap",
        linkUrl: "hats/wolf-cap",
        imageUrl: "https://i.ibb.co/1f2nWMM/wolf-cap.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 14,
      },
      {
        id: 9,
        title: "Blue Snapback",
        routeName: "blue-snapback",
        linkUrl: "hats/blue-snapback",
        imageUrl: "https://i.ibb.co/X2VJP2W/blue-snapback.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 16,
      },
    ],
  },
  sneakers: {
    id: 2,
    title: "Sneakers",
    routeName: "sneakers",
    imageUrl: "https://i.ibb.co/0jqHpnp/sneakers.png",
    linkUrl: "creations/sneakers",
    items: [
      {
        id: 10,
        title: "Adidas NMD",
        routeName: "adidas-nmd",
        linkUrl: "sneakers/adidas-nmd",
        imageUrl: "https://i.ibb.co/0s3pdnc/adidas-nmd.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 220,
      },
      {
        id: 11,
        title: "Adidas Yeezy",
        routeName: "adidas-yeezy",
        linkUrl: "sneakers/adidas-yeezy",
        imageUrl: "https://i.ibb.co/dJbG1cT/yeezy.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 280,
      },
      {
        id: 12,
        title: "Black Converse",
        routeName: "black-converse",
        linkUrl: "sneakers/black-converse",
        imageUrl: "https://i.ibb.co/bPmVXyP/black-converse.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 110,
      },
      {
        id: 13,
        title: "Nike White AirForce",
        routeName: "nike-white-airforce",
        linkUrl: "sneakers/nike-white-airforce",
        imageUrl: "https://i.ibb.co/1RcFPk0/white-nike-high-tops.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 160,
      },
      {
        id: 14,
        title: "Nike Red High Tops",
        routeName: "nike-red-high-tops",
        linkUrl: "sneakers/nike-red-high-tops",
        imageUrl: "https://i.ibb.co/QcvzydB/nikes-red.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 160,
      },
      {
        id: 15,
        title: "Nike Brown High Tops",
        routeName: "nike-brown-high-tops",
        linkUrl: "sneakers/nike-brown-high-tops",
        imageUrl: "https://i.ibb.co/fMTV342/nike-brown.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 160,
      },
      {
        id: 16,
        title: "Air Jordan Limited",
        routeName: "air-jordan-limited",
        linkUrl: "sneakers/air-jordan-limited",
        imageUrl: "https://i.ibb.co/w4k6Ws9/nike-funky.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 190,
      },
      {
        id: 17,
        title: "Timberlands",
        routeName: "timberlands",
        linkUrl: "sneakers/timberlands",
        imageUrl: "https://i.ibb.co/Mhh6wBg/timberlands.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 200,
      },
    ],
  },
  jackets: {
    id: 3,
    title: "Jackets",
    routeName: "jackets",
    imageUrl: "https://i.ibb.co/px2tCc3/jackets.png",
    linkUrl: "creations/jackets",
    items: [
      {
        id: 18,
        title: "Black Jean Shearling",
        routeName: "black-jean-shearling",
        linkUrl: "jackets/black-jean-shearling",
        imageUrl: "https://i.ibb.co/XzcwL5s/black-shearling.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 125,
      },
      {
        id: 19,
        title: "Blue Jean Jacket",
        routeName: "blue-jean-jacket",
        linkUrl: "jackets/blue-jean-jacket",
        imageUrl: "https://i.ibb.co/mJS6vz0/blue-jean-jacket.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 90,
      },
      {
        id: 20,
        title: "Grey Jean Jacket",
        routeName: "grey-jean-jacket",
        linkUrl: "jackets/grey-jean-jacket",
        imageUrl: "https://i.ibb.co/N71k1ML/grey-jean-jacket.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 90,
      },
      {
        id: 21,
        title: "Brown Shearling",
        routeName: "brown-shearling",
        linkUrl: "jackets/brown-shearling",
        imageUrl: "https://i.ibb.co/s96FpdP/brown-shearling.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 165,
      },
      {
        id: 22,
        title: "Tan Trench",
        routeName: "tan-trench",
        linkUrl: "jackets/tan-trench",
        imageUrl: "https://i.ibb.co/M6hHc3F/brown-trench.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 185,
      },
    ],
  },
  womens: {
    id: 4,
    title: "Womens",
    imageUrl: "https://i.ibb.co/GCCdy8t/womens.png",
    linkUrl: "creations/womens",
    routeName: "womens",
    items: [
      {
        id: 23,
        title: "Blue Tanktop",
        routeName: "blue-tanktop",
        linkUrl: "womens/blue-tanktop",
        imageUrl: "https://i.ibb.co/7CQVJNm/blue-tank.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 25,
      },
      {
        id: 24,
        title: "Floral Blouse",
        routeName: "floral-blouse",
        linkUrl: "womens/floral-blouse",
        imageUrl: "https://i.ibb.co/4W2DGKm/floral-blouse.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 20,
      },
      {
        id: 25,
        title: "Floral Dress",
        routeName: "floral-dress",
        linkUrl: "womens/floral-dress",
        imageUrl: "https://i.ibb.co/KV18Ysr/floral-skirt.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 80,
      },
      {
        id: 26,
        title: "Red Dots Dress",
        routeName: "red-dots-dress",
        linkUrl: "womens/red-dots-dress",
        imageUrl: "https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 80,
      },
      {
        id: 27,
        title: "Striped Sweater",
        routeName: "striped-sweater",
        linkUrl: "womens/striped-sweater",
        imageUrl: "https://i.ibb.co/KmSkMbH/striped-sweater.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 45,
      },
      {
        id: 28,
        title: "Yellow Track Suit",
        routeName: "yellow-track-suit",
        linkUrl: "womens/yellow-track-suit",
        imageUrl: "https://i.ibb.co/v1cvwNf/yellow-track-suit.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 135,
      },
      {
        id: 29,
        title: "White Blouse",
        routeName: "white-blouse",
        linkUrl: "womens/white-blouse",
        imageUrl: "https://i.ibb.co/qBcrsJg/white-vest.png",
        carouselImages: [
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
          "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        ],
        price: 20,
      },
    ],
  },
};

export default SHOP_DATA;
